spring.application.name=mobile-money-api

spring.datasource.url=jdbc:mariadb://localhost:3306/MOBILEMONEY
spring.datasource.username=root
spring.datasource.password=kenainy11
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

api.prefix=/api/v1

jwt.secret=MaCleTresSecreteEtTresLonguePourLeProjetMobileMoney2026
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kenainyravelomanana@gmail.com
spring.mail.password=fhojtfbwfbfyzepk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true